##Local MongoDB config
spring:
  mvc:
    static-path-pattern: /static/**
  data:
    mongodb:
#      uri: mongodb+srv://thanhlam0241:thanhlam0241@iot.npxkz7m.mongodb.net/?retryWrites=true&w=majority
      host: localhost
      port: 27017
      database: iot
      #username: admin
      #password: password

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method

rabbitmq:
#  uri: amqps://ubhptxwu:eh0iTQ0D22adEkSc9kyb2gB8hTZ_yVOt@armadillo.rmq.cloudamqp.com/ubhptxwu
  host: amqps://ubhptxwu:eh0iTQ0D22adEkSc9kyb2gB8hTZ_yVOt@armadillo.rmq.cloudamqp.com/ubhptxwu
  port: 5672
  username: ubhptxwu
  password: eh0iTQ0D22adEkSc9kyb2gB8hTZ_yVOt
  queue: iot-queue
  exchange: iot-exchange
  routing-key: iot-routing-key

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate=DEBUG:
