##Local MongoDB config
spring:
  mvc:
    static-path-pattern: /static/**
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iot
      #username: admin
      #password: password

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: iot-queue
  exchange: iot-exchange
  routing-key: iot-routing-key

